var express = require("express")
var router = express.Router()
var HomeController = require("../controllers/HomeController")
var UserController = require("../controllers/UserController")
var CategoryController = require("../controllers/categoryController")
var AdminAuth = require("../middleware/AdminAuth")

router.get('/', HomeController.index)
router.post('/user', UserController.create)
router.get("/users", AdminAuth, UserController.index)
router.get("/user/:id", UserController.findUser)
router.get("/user/email/:email", UserController.findEmailUser)
router.put("/user", UserController.edit)
router.delete("/user/:id", AdminAuth, UserController.remove)
router.post("/recoverpassword", UserController.recoverPassword)
router.post("/changepassword", UserController.changePassword)
router.post("/login", UserController.login)
router.post("/category", CategoryController.create)
router.get("/categories", CategoryController.getCategories)
router.get("/category/:id", CategoryController.findCategory)
router.delete("/category/:id", CategoryController.delete)
router.patch("/category/:id/archive", CategoryController.archiveCategory)
router.get("/categories/archived", CategoryController.getArchivedCategories)
router.patch("/category/:id/unarchive", CategoryController.unarchiveCategory)
router.patch("/category/:id", CategoryController.updateCategory)

module.exports = router
